apiVersion: batch/v1
kind: CronJob
metadata:
  name: aajtak-cronjob
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: pavan0111/aajtak-scraper:latest
              imagePullPolicy: Always
              volumeMounts:
                - name: output
                  mountPath: /usr/src/app
          restartPolicy: OnFailure
          volumes:
            - name: output
              hostPath:
                path: /home/ubuntu/aajtak-data
                type: DirectoryOrCreate
